### ISSUE TITLE
Install on WSL Ubuntu

### ISSUE THREAD

**Issue by Eudorajab1** [ali96343/py4web-chat#1]
Have installed from scratch into a new venv on wsl ubuntu with redis-server running. App gets loaded okay but when I go to access the app localhost:80000/chat I get the red 404 error page. Is this WSL related or?

**Comment by ali96343** [comment]
Hi!

Please, in yout env

pip install redis
pip install python-socketio

**Comment by ali96343** [comment]
@Eudorajab1, chat-server is independent of the linux-distibution
(
Also, here are some new  and raw ideas about chat-server 
https://github.com/ali96343/lvsio
)
